# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='GoalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Goal')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.EntryResponse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.EntryResponse')),
            ],
        ),
    ]
