# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entryresponse_goalresponse_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='responses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='entryresponse',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
