# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20161031_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='morning',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
