# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_morning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='morning',
            name='more',
            field=models.TextField(default='', verbose_name='Additional Reflection'),
        ),
    ]
