# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_morning_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amazing1', models.CharField(max_length=100, verbose_name='3 Amazing things that happened today are...')),
                ('amazing2', models.CharField(max_length=100, verbose_name='3 Amazing things that happened today are...')),
                ('amazing3', models.CharField(max_length=100, verbose_name='3 Amazing things that happened today are...')),
                ('better1', models.CharField(max_length=100, verbose_name='How could I have made today better?')),
                ('better2', models.CharField(max_length=100, verbose_name='How could I have made today better?')),
                ('more', models.TextField(default='', verbose_name='Additional Reflection')),
            ],
        ),
    ]
