# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_evening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evening',
            name='amazing1',
            field=models.CharField(max_length=200, verbose_name='3 Amazing things that happened today are...'),
        ),
        migrations.AlterField(
            model_name='evening',
            name='amazing2',
            field=models.CharField(max_length=200, verbose_name='3 Amazing things that happened today are...'),
        ),
        migrations.AlterField(
            model_name='evening',
            name='amazing3',
            field=models.CharField(max_length=200, verbose_name='3 Amazing things that happened today are...'),
        ),
        migrations.AlterField(
            model_name='evening',
            name='better1',
            field=models.CharField(max_length=200, verbose_name='How could I have made today better?'),
        ),
        migrations.AlterField(
            model_name='evening',
            name='better2',
            field=models.CharField(max_length=200, verbose_name='How could I have made today better?'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='affirm1',
            field=models.CharField(max_length=200, verbose_name='Daily Affirmations, I am...'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='affirm2',
            field=models.CharField(max_length=200, verbose_name='Daily Affirmations, I am...'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='grateful1',
            field=models.CharField(max_length=200, verbose_name='I am grateful for...'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='grateful2',
            field=models.CharField(max_length=200, verbose_name='I am grateful for...'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='grateful3',
            field=models.CharField(max_length=200, verbose_name='I am grateful for...'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='great1',
            field=models.CharField(max_length=200, verbose_name='What would make today great?'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='great2',
            field=models.CharField(max_length=200, verbose_name='What would make today great?'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='great3',
            field=models.CharField(max_length=200, verbose_name='What would make today great?'),
        ),
    ]
