# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20161102_1224'),
    ]

    operations = [
    	migrations.RenameField('Question', 'entry', 'journal'),
    	migrations.RenameField('Journal', 'entry_type', 'journal_type'),
    ]
