# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20161102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 19, 31, 27, 270668, tzinfo=utc)),
        ),
    ]
