# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20161102_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='M', max_length=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 21, 9, 35, 685440, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='additionalanswer',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.Response'),
            preserve_default=False,
        ),
    ]
