# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20161102_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalanswer',
            name='question',
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 9, 22, 23, 10, 81051, tzinfo=utc)),
        ),
    ]
