# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20161102_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_type',
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(default='morning', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 17, 20, 3, 231560, tzinfo=utc)),
        ),
    ]
