# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20161103_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('F', 'First'), ('L', 'Last'), ('M', 'Middle')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 10, 18, 12, 34, 858631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='response',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal'),
        ),
    ]
