# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_auto_20161103_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 19, 20, 43, 25, 418258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
