# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_auto_20161118_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
