# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_auto_20161216_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('goals', models.BooleanField(default=True)),
                ('events', models.BooleanField(default=True)),
            ],
        ),
    ]
