# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_journalsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
