# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20170109_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
